name: real_beez
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and general dependencies
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.1.0
  flutter_custom_clippers: ^2.1.0
  flutter_svg: ^2.0.9
  video_player: ^2.6.0
  table_calendar: ^3.1.2

  # Location & maps
  google_maps_flutter: ^2.13.1
  geolocator: ^13.0.1


  maplibre_gl:
    git:
      url: https://github.com/m0nac0/flutter-maplibre-gl.git
      ref: main
      path: maplibre_gl

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  flutter_launcher_icons: ^0.14.4   

flutter_icons:
  android: true                   
  ios: true
  image_path: "assets/logo/bee.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/videos/
    - static_data.json
